# Generated by Django 2.0.6 on 2018-06-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default='no-address', max_length=30),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='00000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
